### ISSUE TITLE
mac 玩不了？？

### ISSUE THREAD

**Issue by makeloveandroid** [Efaker/FakerAndroid#1]
mac 玩不了？？mac 玩不了？？

**Comment by Efaker** [comment]
普通apk可以，但是il2cpp游戏apk无法生成c++脚手架

**Comment by liangpengfei** [comment]
@Efaker 普通的安装包有报错。
```
checking or making il2cpp scaffolding...
java.io.FileNotFoundException: shareTo/app/build.gradle (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.faker.android.FileUtil.autoReplaceStr(FileUtil.java:16)
	at com.faker.android.Importer.mergeSourceCode(Importer.java:86)
	at com.faker.android.IImporter.doImport(IImporter.java:46)
	at com.faker.android.FakerTransfer.translate(FakerTransfer.java:16)
	at brut.apktool.Main.cmdFakeProject(Main.java:129)
	at brut.apktool.Main.main(Main.java:77)
```

**Comment by Efaker** [comment]
@liangpengfei 加我QQ安装包给我一下

**Comment by Efaker** [comment]
已经修复！经测试Mac可以正常运行，请使用最新的jar包
