### ISSUE TITLE
执行jar报空指针异常

### ISSUE THREAD

**Issue by itzuo** [Efaker/FakerAndroid#14]
十二月 17, 2020 9:54:40 上午 brut.androlib.Androlib decodeUnknownFiles
信息: Copying unknown files...
十二月 17, 2020 9:54:40 上午 brut.androlib.Androlib writeOriginalFiles
信息: Copying original files...
Exception in thread "pool-2-thread-1" java.lang.NullPointerException
	at faker.android.decoder.il2cpp.Il2cppBinary.dumpIl2cpp(Il2cppBinary.java:31)
	at faker.android.decoder.transforms.Il2cppDumper.transform(Il2cppDumper.java:20)
	at faker.android.decoder.pipeline.TransformManager.action(TransformManager.java:29)
	at faker.android.decoder.api.Transfer.translate(Transfer.java:41)
	at FilechooserController$TestTask.run(FilechooserController.java:131)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Efaker** [comment]
是最新的release版本吗

**Comment by Efaker** [comment]
已经更新了release包了，你是不用使用的非windows？再试一下
