### ISSUE TITLE
卡在了Translating dexes to java scaffodding jar

### ISSUE THREAD

**Issue by dmxzz** [Efaker/FakerAndroid#17]
I: Translating dexes to java scaffodding jar....
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.HashMap.newNode(Unknown Source)
        at java.util.HashMap.putVal(Unknown Source)
        at java.util.HashMap.put(Unknown Source)
        at java.util.HashSet.add(Unknown Source)
        at com.googlecode.dex2jar.ir.ts.UniqueQueue.add(UniqueQueue.java:28)
        at com.googlecode.dex2jar.ir.ts.UniqueQueue.addAll(UniqueQueue.java:18)
        at com.googlecode.dex2jar.ir.ts.UnSSATransformer$LiveA.markUsed(UnSSATransformer.java:428)
        at com.googlecode.dex2jar.ir.ts.UnSSATransformer$LiveA.analyzeValue(UnSSATransformer.java:401)
        at com.googlecode.dex2jar.ir.ts.an.BaseAnalyze.analyze(BaseAnalyze.java:70)
        at com.googlecode.dex2jar.ir.ts.UnSSATransformer.transform(UnSSATransformer.java:300)
        at faker.android.decoder.dex2jar.PatchDex2jar$2.optimize(PatchDex2jar.java:147)
        at com.googlecode.d2j.dex.Dex2Asm.convertCode(Dex2Asm.java:452)
        at com.googlecode.d2j.dex.ExDex2Asm.convertCode(ExDex2Asm.java:40)
        at faker.android.decoder.dex2jar.PatchDex2jar$2.convertCode(PatchDex2jar.java:107)
        at com.googlecode.d2j.dex.Dex2Asm.convertMethod(Dex2Asm.java:596)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:444)
        at com.googlecode.d2j.dex.Dex2Asm.convertClass(Dex2Asm.java:357)
        at com.googlecode.d2j.dex.Dex2Asm.convertDex(Dex2Asm.java:460)
        at faker.android.decoder.dex2jar.PatchDex2jar.doTranslate(PatchDex2jar.java:155)
        at faker.android.decoder.dex2jar.PatchDex2jar.to(PatchDex2jar.java:263)
        at faker.android.decoder.dex2jar.Dex2jar.toJar(Dex2jar.java:36)
        at faker.android.decoder.transforms.DexToJar.transform(DexToJar.java:24)
        at faker.android.decoder.pipeline.TransformManager.action(TransformManager.java:29)
        at faker.android.decoder.api.Transfer.translate(Transfer.java:41)
        at faker.android.decoder.Main.cmdFakeProject(Main.java:126)
        at faker.android.decoder.Main.main(Main.java:77)

**Comment by dmxzz** [comment]
解决了加参数 java -jar -Xms800m -Xmx800m FakerAndroid.jar fk xxx.apk

**Comment by dmxzz** [comment]
但是GUI版本的Jar好像不能

**Comment by Drawlone** [comment]
可以的，不行就继续加大数值
