### ISSUE TITLE
运行时错误

### ISSUE THREAD

**Issue by 103945089** [Efaker/FakerAndroid#4]
你好，请问，逆向后的包。直接跑包的时候，总是会有包爆Error inflating class xxxxxxx

我看了下，感觉是有些自定义的包会报这个错。 xml里面报错的这个控件，能再class.jar里面查找到，但是还是会报错
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.joydao.football.time/net.joydao.football.time.activity.MainActivity}: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class net.joydao.football.time.view.FlagRadioButton
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6806)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: android.view.InflateException: Binary XML file line #14: Binary XML file line #14: Error inflating class net.joydao.football.time.view.FlagRadioButton
     Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class net.joydao.football.time.view.FlagRadioButton

**Comment by 103945089** [comment]
好的，前辈辛苦了

**Comment by Efaker** [comment]
原包方便提供一下嗎？

**Comment by sxdqx** [comment]
错误: 找不到或无法加载主类 FakerAndroid.jar
原因: java.lang.ClassNotFoundException: FakerAndroid.jar

**Comment by Efaker** [comment]
自定义控件丢失属性id问题已经解决
